# Dockerizing a Mule application
# Version:  All Mule versions >= 3.0
# Based on:  pr3d4t0r/mule

FROM                    pr3d4t0r/mule:latest
MAINTAINER              Eugene Ciurana <muledocker@eugeneciurana.com>


# Define the application configuration - nice and easy!

ADD                     mule-docker-test-a/target/mule-docker-test-a-1.0.0-SNAPSHOT.zip /opt/mule-standalone-3.5.0/apps/

